# BS_Agent_DingDan v2 清洗 Pipeline 复核

本 notebook 仅用于 BS_Agent_DingDan v2 清洗 pipeline 的人工复核与汇报展示。

正式清洗逻辑统一来自 `alg.cleaning.bs_agent_dingdan_pipeline.run_bs_agent_dingdan_cleaning_pipeline`。

notebook 不再维护独立清洗逻辑。

## 0. 字段字典

字段解释请查看 `docs/data_dictionary/BS_Agent_DingDan_v2_outputs.md`。本 notebook 只展示 pipeline 结果，不维护独立字段口径。

## 1. 环境与路径配置

In [23]:
from pathlib import Path
import sys

import pandas as pd

PROJECT_ROOT = Path.cwd()
if PROJECT_ROOT.name == "notebooks":
    PROJECT_ROOT = PROJECT_ROOT.parent

SRC_ROOT = PROJECT_ROOT / "src"
if str(SRC_ROOT) not in sys.path:
    sys.path.insert(0, str(SRC_ROOT))

from alg.cleaning.bs_agent_dingdan_pipeline import run_bs_agent_dingdan_cleaning_pipeline
from alg.cleaning.bs_agent_dingdan import load_env

pd.set_option("display.max_columns", 120)
pd.set_option("display.width", 180)

sql_database_url, sql_table = load_env(PROJECT_ROOT)

sample_mode = True
max_rows = 100000
output_format = "parquet"
generate_model = True
generate_quality_report = True
generate_clean = True
generate_audit = True
return_dataframes = True

print(f"project_root={PROJECT_ROOT}")
print(f"sample_mode={sample_mode}, max_rows={max_rows}, table={sql_table}")
print("SQL_DATABASE_URL configured:", bool(sql_database_url))

project_root=c:\Users\admin\Myprojects\for_git\algo_main
sample_mode=True, max_rows=100000, table=BS_Agent_DingDan
SQL_DATABASE_URL configured: True

## 2. 运行 pipeline

In [24]:
result = run_bs_agent_dingdan_cleaning_pipeline(
    sql_database_url=sql_database_url,
    table_name=sql_table,
    output_dir="exports",
    output_format=output_format,
    max_rows=max_rows,
    sample_mode=sample_mode,
    generate_model=generate_model,
    generate_clean=generate_clean,
    generate_audit=generate_audit,
    generate_quality_report=generate_quality_report,
    return_dataframes=return_dataframes,
)

result["row_count"], result["model_columns"], result["output_paths"]

(100000,
 ['row_uid',
  'order_detail_id',
  'purchase_time',
  'province_code',
  'city_code',
  'county_code',
  'region_dirty_flag',
  'hospital_code',
  'drug_code',
  'drug_category_code',
  'distributor_code',
  'manufacturer_code',
  'hospital_level_code',
  'ownership_type_code',
  'order_phase_code',
  'delivery_state_code',
  'order_terminal_flag',
  'order_failure_flag',
  'return_quantity',
  'raw_sensitive_purchase_quantity',
  'raw_sensitive_purchase_amount',
  'raw_sensitive_delivery_quantity',
  'raw_sensitive_delivery_amount',
  'raw_sensitive_arrival_quantity',
  'raw_sensitive_arrival_amount',
  'delivery_rate',
  'arrival_rate',
  'overall_arrival_rate',
  'delivery_amount_to_purchase_amount_ratio',
  'arrival_amount_to_delivery_amount_ratio',
  'arrival_amount_to_purchase_amount_ratio'],
 {'review_outputs': {'clean_sample_v2': 'C:\\Users\\admin\\Myprojects\\for_git\\algo_main\\exports\\clean\\bs_agent_dingdan_clean_sample_v2.csv',
   'audit_sample': 'C:\\Users\\admin\\Myprojects\\for_git\\algo_main\\exports\\clean\\bs_agent_dingdan_audit_sample.csv',
   'field_quality_gate_v2': 'C:\\Users\\admin\\Myprojects\\for_git\\algo_main\\exports\\eda\\field_quality_gate_v2.csv',
   'numeric_desensitization_report_v2': 'C:\\Users\\admin\\Myprojects\\for_git\\algo_main\\exports\\eda\\numeric_desensitization_report_v2.csv',
   'order_status_mapping_coverage': 'C:\\Users\\admin\\Myprojects\\for_git\\algo_main\\exports\\eda\\order_status_mapping_coverage.csv',
   'order_status_suspicious_mapping': 'C:\\Users\\admin\\Myprojects\\for_git\\algo_main\\exports\\eda\\order_status_suspicious_mapping.csv',
   'order_status_lifecycle_map': 'C:\\Users\\admin\\Myprojects\\for_git\\algo_main\\exports\\mappings\\order_status_lifecycle_map.csv',
   'quality_report': 'C:\\Users\\admin\\Myprojects\\for_git\\algo_main\\exports\\eda\\bs_agent_dingdan_quality_report_v2.md'},
  'model_base': {'parquet': 'C:\\Users\\admin\\Myprojects\\for_git\\algo_main\\data\\03_cleaned\\bs_agent_dingdan_model_base.parquet'}})

## 3. 展示三张核心表

In [12]:
clean_v2 = result["dataframes"]["clean"]
model_base = result["dataframes"]["model_base"]
audit = result["dataframes"]["audit"]

display(clean_v2.head())
display(model_base.head())
display(audit.head())

clean_v2.shape, model_base.shape, audit.shape

,row_uid,order_detail_id,purchase_time,province_code,city_code,county_code,drug_code,drug_name,product_name,drug_category_code,drug_category_raw,hospital_code,hospital_name,hospital_level_raw,hospital_level_label,hospital_level_code,ownership_type_code,ownership_type_raw,distributor_code,distributor_name,manufacturer_code,manufacturer_name,order_status_raw,order_status_norm,order_phase_code,order_phase_label,delivery_state_code,delivery_state_label,order_terminal_flag,order_failure_flag,needs_manual_review,return_quantity,raw_sensitive_purchase_price,raw_sensitive_purchase_quantity,raw_sensitive_purchase_amount,raw_sensitive_delivery_quantity,raw_sensitive_delivery_amount,raw_sensitive_arrival_quantity,raw_sensitive_arrival_amount,region_dirty_flag,delivery_rate,arrival_rate,overall_arrival_rate,delivery_amount_to_purchase_amount_ratio,arrival_amount_to_delivery_amount_ratio,arrival_amount_to_purchase_amount_ratio,mapping_failure_reason
0,996BF6CF-391B-4C5A-A528-4C5229A34A59,52470792591376bbfbcb76d777622338,2012-08-05 00:00:00,340000,340300,340323,4b98de3c6d633e40a667e553874075f0,注射用磷霉素钠,NaN,2,全身用抗感染药/全身用抗菌药/其他抗菌药/其他抗菌药,YL341870,固镇县刘集镇中心卫生院,二级,二级,2,1,公立,YLQY001064,安徽省恒济医药有限公司,F9BDA11C2EE443F49615B9AD6AFBD4AA,哈药集团制药总厂,已确认,已确认,30,confirmed,2,confirmed_not_dispatched,0,0,False,0.0,4.92,300.0,1475.0,0.0,0.0,0.0,0.0,0,0.0,NaN,0.0,0.0,NaN,0.0,
1,67E98737-4563-4F18-84B1-E75DF2E8D5D0,CA1B62EB-B61B-4E8C-8E5C-3F2559EB8135,2015-08-26 23:07:00,510000,510100,510104,XC08CAL013A025010403705,拉西地平片,司乐平,4,心血管系统/钙通道阻滞剂/主要作用于血管的选择性钙通道阻滞剂/二氢吡啶衍生物类,YL514812,成都市第二人民医院,三级,三级,3,1,公立,YLQY022489,国药控股四川医药股份有限公司,E50FC20840554CF79ACAEF2582AE63BD,哈药集团三精明水药业有限公司,入库,入库,60,received,5,received,1,0,False,0.0,63.33,510.0,32300.0,510.0,32300.0,510.0,32300.0,0,1.0,1.0,1.0,1.0,1.0,1.0,
2,6E6555D6-F5F0-46DA-9112-BD01CB1788AC,98ad0ae7163cc6bcf665a441ad6aa68a,2012-11-05 00:00:00,340000,340400,340422,XJ01CAA040E001020303712,阿莫西林胶囊,益萨林,1,全身用抗感染药/全身用抗菌药/β-内酰胺类抗菌药，青霉素类/广谱青霉素类,YL344077,寿县张李乡卫生院,未定级,未定级,0,1,公立,YLQY012060,国药控股六安有限公司,F9BDA11C2EE443F49615B9AD6AFBD4AA,哈药集团制药总厂,已确认,已确认,30,confirmed,2,confirmed_not_dispatched,0,0,False,0.0,6.95,300.0,2085.0,0.0,0.0,0.0,0.0,0,0.0,NaN,0.0,0.0,NaN,0.0,
3,A93EBD95-D30D-441D-BBD3-B61515FB4051,92c341a7caaf7044eae75eae9d0a085b,2012-12-09 00:00:00,340000,341300,341302,XJ01CAA040E001020303712,阿莫西林胶囊,益萨林,1,全身用抗感染药/全身用抗菌药/β-内酰胺类抗菌药，青霉素类/广谱青霉素类,YL342477,宿州市埇桥区西二铺镇卫生院,未定级,未定级,0,1,公立,YLQY004784,安徽华康医药集团有限公司,F9BDA11C2EE443F49615B9AD6AFBD4AA,哈药集团制药总厂,已确认,已确认,30,confirmed,2,confirmed_not_dispatched,0,0,False,0.0,6.95,150.0,1042.5,0.0,0.0,0.0,0.0,0,0.0,NaN,0.0,0.0,NaN,0.0,
4,EBB48B80-0501-47FD-8BB2-05E8C6962E96,147e56044653c7d08af73ccd1c6487d6,2012-10-16 00:00:00,340000,341600,341621,XJ01CAA040E001020303712,阿莫西林胶囊,益萨林,1,全身用抗感染药/全身用抗菌药/β-内酰胺类抗菌药，青霉素类/广谱青霉素类,YL344150,涡阳县青町镇卫生院,未定级,未定级,0,1,公立,YLQY000164,安徽省亳州市药品采购供应站,F9BDA11C2EE443F49615B9AD6AFBD4AA,哈药集团制药总厂,已确认,已确认,30,confirmed,2,confirmed_not_dispatched,0,0,False,0.0,6.95,30.0,208.5,0.0,0.0,0.0,0.0,0,0.0,NaN,0.0,0.0,NaN,0.0,

,row_uid,order_detail_id,purchase_time,province_code,city_code,county_code,region_dirty_flag,hospital_code,drug_code,drug_category_code,distributor_code,manufacturer_code,hospital_level_code,ownership_type_code,order_phase_code,delivery_state_code,order_terminal_flag,order_failure_flag,return_quantity,raw_sensitive_purchase_quantity,raw_sensitive_purchase_amount,raw_sensitive_delivery_quantity,raw_sensitive_delivery_amount,raw_sensitive_arrival_quantity,raw_sensitive_arrival_amount,delivery_rate,arrival_rate,overall_arrival_rate,delivery_amount_to_purchase_amount_ratio,arrival_amount_to_delivery_amount_ratio,arrival_amount_to_purchase_amount_ratio
0,996BF6CF-391B-4C5A-A528-4C5229A34A59,52470792591376bbfbcb76d777622338,2012-08-05 00:00:00,340000,340300,340323,0,YL341870,4b98de3c6d633e40a667e553874075f0,2,YLQY001064,F9BDA11C2EE443F49615B9AD6AFBD4AA,2,1,30,2,0,0,0.0,300.0,1475.0,0.0,0.0,0.0,0.0,0.0,NaN,0.0,0.0,NaN,0.0
1,67E98737-4563-4F18-84B1-E75DF2E8D5D0,CA1B62EB-B61B-4E8C-8E5C-3F2559EB8135,2015-08-26 23:07:00,510000,510100,510104,0,YL514812,XC08CAL013A025010403705,4,YLQY022489,E50FC20840554CF79ACAEF2582AE63BD,3,1,60,5,1,0,0.0,510.0,32300.0,510.0,32300.0,510.0,32300.0,1.0,1.0,1.0,1.0,1.0,1.0
2,6E6555D6-F5F0-46DA-9112-BD01CB1788AC,98ad0ae7163cc6bcf665a441ad6aa68a,2012-11-05 00:00:00,340000,340400,340422,0,YL344077,XJ01CAA040E001020303712,1,YLQY012060,F9BDA11C2EE443F49615B9AD6AFBD4AA,0,1,30,2,0,0,0.0,300.0,2085.0,0.0,0.0,0.0,0.0,0.0,NaN,0.0,0.0,NaN,0.0
3,A93EBD95-D30D-441D-BBD3-B61515FB4051,92c341a7caaf7044eae75eae9d0a085b,2012-12-09 00:00:00,340000,341300,341302,0,YL342477,XJ01CAA040E001020303712,1,YLQY004784,F9BDA11C2EE443F49615B9AD6AFBD4AA,0,1,30,2,0,0,0.0,150.0,1042.5,0.0,0.0,0.0,0.0,0.0,NaN,0.0,0.0,NaN,0.0
4,EBB48B80-0501-47FD-8BB2-05E8C6962E96,147e56044653c7d08af73ccd1c6487d6,2012-10-16 00:00:00,340000,341600,341621,0,YL344150,XJ01CAA040E001020303712,1,YLQY000164,F9BDA11C2EE443F49615B9AD6AFBD4AA,0,1,30,2,0,0,0.0,30.0,208.5,0.0,0.0,0.0,0.0,0.0,NaN,0.0,0.0,NaN,0.0

,row_uid,order_detail_id,raw_province_code,raw_city_code,province_code,city_code,county_code,region_dirty_flag,order_status_raw,order_status_norm,order_phase_code,order_phase_label,delivery_state_code,delivery_state_label,order_terminal_flag,order_failure_flag,needs_manual_review,mapping_failure_reason,drug_code,insurance_drug_code,drug_code_match_flag,drug_code_conflict_flag,drug_category_raw,drug_category_code,product_name,hospital_level_raw,hospital_level_label,hospital_level_code,hospital_level_detail_raw,ownership_type_raw,ownership_type_code,enterprise_code_raw,manufacturer_code,manufacturer_name,distributor_code,distributor_name,delivery_rate,arrival_rate,overall_arrival_rate
0,996BF6CF-391B-4C5A-A528-4C5229A34A59,52470792591376bbfbcb76d777622338,340000,340300,340000,340300,340323,0,已确认,已确认,30,confirmed,2,confirmed_not_dispatched,0,0,False,,4b98de3c6d633e40a667e553874075f0,XJ01XXL096B001040203712,0,0,全身用抗感染药/全身用抗菌药/其他抗菌药/其他抗菌药,2,NaN,二级,二级,2,二级,公立,1,207,F9BDA11C2EE443F49615B9AD6AFBD4AA,哈药集团制药总厂,YLQY001064,安徽省恒济医药有限公司,0.0,NaN,0.0
1,67E98737-4563-4F18-84B1-E75DF2E8D5D0,CA1B62EB-B61B-4E8C-8E5C-3F2559EB8135,510000,510100,510000,510100,510104,0,入库,入库,60,received,5,received,1,0,False,,XC08CAL013A025010403705,XC08CAL013A025010403705,1,0,心血管系统/钙通道阻滞剂/主要作用于血管的选择性钙通道阻滞剂/二氢吡啶衍生物类,4,司乐平,三级,三级,3,三级甲等,公立,1,207,E50FC20840554CF79ACAEF2582AE63BD,哈药集团三精明水药业有限公司,YLQY022489,国药控股四川医药股份有限公司,1.0,1.0,1.0
2,6E6555D6-F5F0-46DA-9112-BD01CB1788AC,98ad0ae7163cc6bcf665a441ad6aa68a,340000,340400,340000,340400,340422,0,已确认,已确认,30,confirmed,2,confirmed_not_dispatched,0,0,False,,XJ01CAA040E001020303712,XJ01CAA040E001020303712,1,0,全身用抗感染药/全身用抗菌药/β-内酰胺类抗菌药，青霉素类/广谱青霉素类,1,益萨林,未定级,未定级,0,一级丙等,公立,1,207,F9BDA11C2EE443F49615B9AD6AFBD4AA,哈药集团制药总厂,YLQY012060,国药控股六安有限公司,0.0,NaN,0.0
3,A93EBD95-D30D-441D-BBD3-B61515FB4051,92c341a7caaf7044eae75eae9d0a085b,340000,341300,340000,341300,341302,0,已确认,已确认,30,confirmed,2,confirmed_not_dispatched,0,0,False,,XJ01CAA040E001020303712,XJ01CAA040E001020303712,1,0,全身用抗感染药/全身用抗菌药/β-内酰胺类抗菌药，青霉素类/广谱青霉素类,1,益萨林,未定级,未定级,0,一级,公立,1,207,F9BDA11C2EE443F49615B9AD6AFBD4AA,哈药集团制药总厂,YLQY004784,安徽华康医药集团有限公司,0.0,NaN,0.0
4,EBB48B80-0501-47FD-8BB2-05E8C6962E96,147e56044653c7d08af73ccd1c6487d6,340000,341600,340000,341600,341621,0,已确认,已确认,30,confirmed,2,confirmed_not_dispatched,0,0,False,,XJ01CAA040E001020303712,XJ01CAA040E001020303712,1,0,全身用抗感染药/全身用抗菌药/β-内酰胺类抗菌药，青霉素类/广谱青霉素类,1,益萨林,未定级,未定级,0,一级甲等,公立,1,207,F9BDA11C2EE443F49615B9AD6AFBD4AA,哈药集团制药总厂,YLQY000164,安徽省亳州市药品采购供应站,0.0,NaN,0.0

((100000, 47), (100000, 31), (100000, 39))

## 4. model_base 字段检查

In [13]:
model_base.columns.tolist()

forbidden = {
    "hospital_name",
    "distributor_name",
    "manufacturer_name",
    "product_name",
    "order_status_raw",
    "hospital_level_raw",
    "hospital_level_label",
    "ownership_type_raw",
    "drug_category_raw",
}
sorted(forbidden.intersection(model_base.columns))

[]

## 5. 主键检查

In [14]:
{
    "clean_row_uid_unique": clean_v2["row_uid"].is_unique,
    "model_row_uid_unique": model_base["row_uid"].is_unique,
    "audit_row_uid_unique": audit["row_uid"].is_unique,
    "clean_order_detail_id_unique": clean_v2["order_detail_id"].is_unique,
    "model_order_detail_id_unique": model_base["order_detail_id"].is_unique,
    "audit_order_detail_id_unique": audit["order_detail_id"].is_unique,
}

{'clean_row_uid_unique': True,
 'model_row_uid_unique': True,
 'audit_row_uid_unique': True,
 'clean_order_detail_id_unique': True,
 'model_order_detail_id_unique': True,
 'audit_order_detail_id_unique': True}

## 6. 订单状态映射检查

In [15]:
display(clean_v2["order_phase_code"].value_counts(dropna=False).sort_index())
display(clean_v2["delivery_state_code"].value_counts(dropna=False).sort_index())
display(clean_v2["needs_manual_review"].value_counts(dropna=False))

display(pd.read_csv(PROJECT_ROOT / "exports/eda/order_status_mapping_coverage.csv"))
display(pd.read_csv(PROJECT_ROOT / "exports/eda/order_status_suspicious_mapping.csv"))

order_phase_code
0       1384
10       129
20      5658
30     29870
40      2862
50      5106
60     43620
70      3127
80       994
90        79
100     7171
Name: count, dtype: int64

delivery_state_code
0     1384
1     5787
2    32732
3     4974
4      132
5    43620
6     4121
7       79
8     4139
9     3032
Name: count, dtype: int64

needs_manual_review
False    98616
True      1384
Name: count, dtype: int64

           metric_group            metric         value
0               summary        total_rows  100000.00000
1               summary       mapped_rows   98616.00000
2               summary     unmapped_rows    1384.00000
3               summary  mapping_coverage       0.98616
4      order_phase_code                 0    1384.00000
5      order_phase_code                10     129.00000
6      order_phase_code                20    5658.00000
7      order_phase_code                30   29870.00000
8      order_phase_code                40    2862.00000
9      order_phase_code                50    5106.00000
10     order_phase_code                60   43620.00000
11     order_phase_code                70    3127.00000
12     order_phase_code                80     994.00000
13     order_phase_code                90      79.00000
14     order_phase_code               100    7171.00000
15  delivery_state_code                 0    1384.00000
16  delivery_state_code                 1    5787.00000
17  delivery_state_code                 2   32732.00000
18  delivery_state_code                 3    4974.00000
19  delivery_state_code                 4     132.00000
20  delivery_state_code                 5   43620.00000
21  delivery_state_code                 6    4121.00000
22  delivery_state_code                 7      79.00000
23  delivery_state_code                 8    4139.00000
24  delivery_state_code                 9    3032.00000
25  order_terminal_flag                -1    1384.00000
26  order_terminal_flag                 0   43625.00000
27  order_terminal_flag                 1   54991.00000
28   order_failure_flag                -1    1384.00000
29   order_failure_flag                 0   91366.00000
30   order_failure_flag                 1    7250.00000

,row_uid,order_detail_id,order_status_raw,order_phase_code,delivery_state_code,order_terminal_flag,order_failure_flag,needs_manual_review,suspicious_reason,suspicious_level
0,E18AAAFA-D72D-43D9-9C53-04AC75FBB499,241128103139045749317821,收货中,0,0,-1,-1,True,receive_keyword_not_received_state,hard
1,1A68539A-F993-4755-AD53-6034BEE363CA,241115093700319576379891,收货中,0,0,-1,-1,True,receive_keyword_not_received_state,hard
2,FF86BB77-4977-4B2E-B6B0-8C0C8145E4FB,S12100002024122701707,已作废(超时未收货),100,8,1,1,False,receive_keyword_not_received_state,hard
3,7711180F-B19F-4174-99F0-5D75529092C4,7c799feabb90d597c9764a02c10d6a44,医疗机构收货确认,0,0,-1,-1,True,receive_keyword_not_received_state,hard
4,1C49383F-E19D-4522-8238-533573878285,e3554f822299e04dfcfed88599f961f2,医疗机构收货确认,0,0,-1,-1,True,receive_keyword_not_received_state,hard
...,...,...,...,...,...,...,...,...,...,...
190,14529FC5-06DB-40A7-A62D-D626EB234049,a2a0c940799a4ce6b98711be7e1c6424,全部出库,0,0,-1,-1,True,dispatch_keyword_not_dispatch_state,hard
191,975719B4-DE0D-4E86-9621-265698571451,e8e17ef0118040d2b4ec9e5981233b80,全部出库,0,0,-1,-1,True,dispatch_keyword_not_dispatch_state,hard
192,4010ADB0-80F1-412B-B67C-1E1ACEFDCC30,4028e9eb14e445bebc25d8c4bdb2f7e1,待出库,0,0,-1,-1,True,dispatch_keyword_not_dispatch_state,hard
193,3BD73960-C38C-4B5A-89EC-EB666E86D30C,d7a15970-86f5-497f-a06b-18dc9b1ef134,已配送未入库,60,5,1,0,False,dispatch_keyword_not_dispatch_state,hard
194,404840AC-1024-4D96-BAC7-A2AF5772AC85,0f291ade-d05f-41a6-9acc-20c1770d4159,已配送未入库,60,5,1,0,False,dispatch_keyword_not_dispatch_state,hard

## 7. 药品编码与地区检查

- `drug_code_match_flag`: 行级一致性检查，表示当前行 `drug_code` 是否等于当前行 `insurance_drug_code`。
- `drug_code_conflict_flag`: 编码级冲突检查，表示同一 `drug_code` 是否对应多个不同 `insurance_drug_code`。
- `region_dirty_flag`: 地区质量控制字段，表示原始 `raw_city_code` 与由 `county_code` 派生的 `city_code` 是否冲突。

In [16]:
summary_tables = []

for table_name, df, column in [
    ("audit", audit, "drug_code_match_flag"),
    ("audit", audit, "drug_code_conflict_flag"),
    ("clean_v2", clean_v2, "region_dirty_flag"),
]:
    vc = (
        df[column]
        .value_counts(dropna=False)
        .rename_axis("value")
        .reset_index(name="count")
    )
    vc.insert(0, "table", table_name)
    vc.insert(1, "field", column)
    vc["rate"] = vc["count"] / len(df)
    summary_tables.append(vc)

quality_flag_summary = pd.concat(summary_tables, ignore_index=True)
quality_flag_summary

      table                    field  value  count     rate
0     audit     drug_code_match_flag      1  76786  0.76786
1     audit     drug_code_match_flag      0  23214  0.23214
2     audit  drug_code_conflict_flag      0  88176  0.88176
3     audit  drug_code_conflict_flag      1  11824  0.11824
4  clean_v2        region_dirty_flag      0  99457  0.99457
5  clean_v2        region_dirty_flag      1    543  0.00543

## 8. 数值脱敏与矛盾检查

In [17]:
numeric_report = pd.read_csv(PROJECT_ROOT / "exports/eda/numeric_desensitization_report_v2.csv")
display(numeric_report.head(50))

display(numeric_report[numeric_report["metric_group"] == "status_quantity_contradiction"])

                                metric_group                                             metric         value
0                                  zero_rate          raw_sensitive_purchase_quantity_zero_rate      0.000010
1                              negative_rate      raw_sensitive_purchase_quantity_negative_rate      0.000990
2                                  zero_rate          raw_sensitive_delivery_quantity_zero_rate      0.395230
3                              negative_rate      raw_sensitive_delivery_quantity_negative_rate      0.000710
4                                  zero_rate           raw_sensitive_arrival_quantity_zero_rate      0.450820
5                              negative_rate       raw_sensitive_arrival_quantity_negative_rate      0.000760
6                                  zero_rate            raw_sensitive_purchase_amount_zero_rate      0.000050
7                              negative_rate        raw_sensitive_purchase_amount_negative_rate      0.000990
8                                  zero_rate            raw_sensitive_delivery_amount_zero_rate      0.395270
9                              negative_rate        raw_sensitive_delivery_amount_negative_rate      0.000710
10                                 zero_rate             raw_sensitive_arrival_amount_zero_rate      0.450860
11                             negative_rate         raw_sensitive_arrival_amount_negative_rate      0.000760
12                                 zero_rate                          return_quantity_zero_rate      0.999950
13                             negative_rate                      return_quantity_negative_rate      0.000000
14                             delivery_rate                                              count  99999.000000
15                             delivery_rate                                                min      0.000000
16                             delivery_rate                                                p25      0.000000
17                             delivery_rate                                                p50      1.000000
18                             delivery_rate                                                p75      1.000000
19                             delivery_rate                                                p95      1.000000
20                             delivery_rate                                                max     75.000000
21                             delivery_rate                            delivery_rate_gt_1_rate      0.000820
22                              arrival_rate                                              count  60477.000000
23                              arrival_rate                                                min      0.000000
24                              arrival_rate                                                p25      1.000000
25                              arrival_rate                                                p50      1.000000
26                              arrival_rate                                                p75      1.000000
27                              arrival_rate                                                p95      1.000000
28                              arrival_rate                                                max     11.000000
29                              arrival_rate                             arrival_rate_gt_1_rate      0.000066
30                      overall_arrival_rate                                              count  99999.000000
31                      overall_arrival_rate                                                min      0.000000
32                      overall_arrival_rate                                                p25      0.000000
33                      overall_arrival_rate                                                p50      1.000000
34                      overall_arrival_rate                                                p75      1.000000
35                      overall_arrival_rate                                                p95      1.000000
36                      overall_arrival_rate                                                max     75.000000
37                      overall_arrival_rate                     overall_arrival_rate_gt_1_rate      0.000780
38  delivery_amount_to_purchase_amount_ratio                                              count  99995.000000
39  delivery_amount_to_purchase_amount_ratio                                                min      0.000000
40  delivery_amount_to_purchase_amount_ratio                                                p25      0.000000
41  delivery_amount_to_purchase_amount_ratio                                                p50      1.000000
42  delivery_amount_to_purchase_amount_ratio                                                p75      1.000000
43  delivery_amount_to_purchase_amount_ratio                                                p95      1.000000
44  delivery_amount_to_purchase_amount_ratio                                                max     75.000000
45  delivery_amount_to_purchase_amount_ratio  delivery_amount_to_purchase_amount_ratio_gt_1_...      0.000820
46   arrival_amount_to_delivery_amount_ratio                                              count  60473.000000
47   arrival_amount_to_delivery_amount_ratio                                                min      0.000000
48   arrival_amount_to_delivery_amount_ratio                                                p25      1.000000
49   arrival_amount_to_delivery_amount_ratio                                                p50      1.000000

                      metric_group                                           metric   value
161  status_quantity_contradiction               received_but_arrival_quantity_zero  4755.0
162  status_quantity_contradiction            dispatched_but_delivery_quantity_zero   320.0
163  status_quantity_contradiction  cancelled_or_failed_but_has_delivery_or_arrival   283.0

## 9. 质量报告展示

In [18]:
quality_report_path = PROJECT_ROOT / "exports/eda/bs_agent_dingdan_quality_report_v2.md"
print(quality_report_path.read_text(encoding="utf-8")[:3000])

# BS_Agent_DingDan v2 清洗质量报告

## 一、处理范围

- 清洗表行数：100000
- clean_v2 字段数：47
- model_base 行数/字段数：100000 / 31
- audit 行数/字段数：100000 / 39

## 二、主键与重复检查

- row_uid 是否唯一：True
- order_detail_id 是否唯一：True
- order_detail_id 重复行数：0

## 三、字段质量

字段级 null 数、null 率、distinct 数请查看 `field_quality_gate_v2.csv`。

## 四、地区字段检查

- region_dirty_flag=0: 99457
- region_dirty_flag=1: 543

## 五、药品编码检查

drug_code 与 insurance_drug_code 一致性：
- drug_code_match_flag=0: 23214
- drug_code_match_flag=1: 76786

drug_code 与 insurance_drug_code 冲突情况：
- drug_code_conflict_flag=0: 88176
- drug_code_conflict_flag=1: 11824

## 六、订单状态映射

- 总行数：100000.0
- 已映射行数：98616.0
- 未映射行数：1384.0
- 映射覆盖率：0.98616

需要人工复核：
- needs_manual_review=False: 98616
- needs_manual_review=True: 1384

订单阶段分布：
- order_phase_code=0: 1384
- order_phase_code=10: 129
- order_phase_code=20: 5658
- order_phase_code=30: 29870
- order_phase_code=40: 2862
- order_phase_code=50: 5106
- order_phase_code=60: 43620
- order_phase_code=70: 3127
- order_phase_code=80: 994
- order_phase_code=90: 79
- order_phase_code=100: 7171

配送状态分布：
- delivery_state_code=0: 1384
- delivery_state_code=1: 5787
- delivery_state_code=2: 32732
- delivery_state_code=3: 4974
- delivery_state_code=4: 132
- delivery_state_code=5: 43620
- delivery_state_code=6: 4121
- delivery_state_code=7: 79
- delivery_state_code=8: 4139
- delivery_state_code=9: 3032

## 七、数值字段检查

zero rate、negative rate、比例分布、gt_1_rate 请查看 `numeric_desensitization_report_v2.csv`。

注意：`gt_1_rate` 使用非空 ratio 行作为分母。

## 八、状态与数量矛盾

- received_but_arrival_quantity_zero: 4755.0
- dispatched_but_delivery_quantity_zero: 320.0
- cancelled_or_failed_but_has_delivery_or_arrival: 283.0

## 九、model_base 使用说明

- `model_base` 是稳定的建模基础表，不是最终 `X_train`。
- `row_uid` 和 `order_detail_id` 是追溯键，不应直接进入 X。
- `purchase_time` 是排序、切分、聚合用的时间索引，不应作为普通连续数值特征直接进入 X。
- `region_dirty_flag` 是质量控制字段，默认不进入 X。
- 状态语义字段在完成、失败、终止、到货、配送质量等任务中可能造成标签泄漏。
- `delivery_rate`、`arrival_rate` 等比例字段来自数量字段，不是配送时长特征。
- 禁止使用 金额 / 数量 推断真实单价，也禁止使用采购价校验金额 / 数量。

## 十、输出路径

- review_outputs.clean_sample_v2: C:\Users\admin\Myprojects\for_git\algo_main\exports\clean\bs_agent_dingdan_clean_sample_v2.csv
- review_outputs.audit_sample: C:\Users\admin\Myprojects\for_git\algo_main\exports\clean\bs_agent_dingdan_audit_sample.csv
- review_outputs.field_quality_gate_v2: C:\Users\admin\Myprojects\for_git\algo_main\exports\eda\field_quality_gate_v2.csv
- review_outputs.numeric_desensitization_report_v2: C:\Users\admin\Myprojects\for_git\algo_main\exports\eda\numeric_desensitization_report_v2.csv
- review_outputs.order_status_mapping_coverage: C:\Users\admin\Myprojects\for_git\algo_main\exports\eda\order_status_mapping_coverage.csv
- review_outputs.order_status_suspicious_mapping: C:\Users\admin\Myprojects\for_git\algo_main\exports\eda\order_status_suspicious_mapping.csv
- review_outputs.order_status_lifecycle_map: C:\Users\admin\Myprojects\for_git\algo_main\exports\mappings\order_status_lifecycle_map.csv
- model_base.parquet: C:\Users\admin\Myprojects\for_

## 10. 汇报结论

- 本 notebook 调用正式 v2 pipeline 生成 model_base。
- model_base 是建模基础表，不是最终 X_train。
- clean/audit 仅用于人工复核。
- `delivery_rate`、`arrival_rate` 等 ratio 字段来自数量/金额比例，不代表时间。
- 状态字段后续进入算法时必须按 cutoff 聚合，避免泄漏。